import {
  Gamepad2,
  Trophy,
  Wallet,
  TrendingUp,
  Target,
  Coins,
  Crown,
  Skull,
  Star,
  Flame,
  CheckCircle,
  XCircle,
  BarChart3,
  Shield,
  Globe,
  Smartphone,
  Package,
  Code,
  Link,
  Users,
  Zap,
  Gem,
  Lock,
  ArrowRight,
  Plus,
  Search,
  Filter,
  Clock,
  Activity,
  ChevronDown,
  X,
  Menu,
  ExternalLink,
  Copy,
  Loader2,
  AlertCircle,
  Info,
  HelpCircle,
  Layers,
  Swords,
  Award,
  Medal,
  Hexagon,
  Link2,
} from "lucide-react";

export const Icons = {
  game: Gamepad2,
  trophy: Trophy,
  wallet: Wallet,
  trending: TrendingUp,
  target: Target,
  coins: Coins,
  crown: Crown,
  skull: Skull,
  star: Star,
  flame: Flame,
  check: CheckCircle,
  cross: XCircle,
  chart: BarChart3,
  shield: Shield,
  globe: Globe,
  smartphone: Smartphone,
  package: Package,
  code: Code,
  link: Link,
  users: Users,
  zap: Zap,
  gem: Gem,
  lock: Lock,
  arrowRight: ArrowRight,
  plus: Plus,
  search: Search,
  filter: Filter,
  clock: Clock,
  activity: Activity,
  chevronDown: ChevronDown,
  close: X,
  menu: Menu,
  externalLink: ExternalLink,
  copy: Copy,
  loading: Loader2,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,
  layers: Layers,
  link2: Link2,
  swords: Swords,
  award: Award,
  medal: Medal,
  hexagon: Hexagon,
};

export const getIcon = (name: keyof typeof Icons, props = {}) => {
  const Icon = Icons[name];
  return Icon ? <Icon {...props} /> : null;
};